#!/usr/bin/env bash
# Deploy Taiga (agile project management — kanban/scrum) on cloud-data,
# using Taiga's OFFICIAL taiga-docker deployment (it bundles its own
# Postgres + RabbitMQ; upstream pins its own versions). Run ONCE, after
# the main cloud-data stack is up:
#
#   sudo bash setup-taiga.sh
#
# Idempotent — re-running updates the checkout but keeps your .env.

set -euo pipefail
log() { echo -e "\e[1;32m==>\e[0m $*"; }
die() { echo -e "\e[1;31mERROR:\e[0m $*" >&2; exit 1; }
[[ $EUID -eq 0 ]] || die "run with sudo"
command -v docker >/dev/null 2>&1 || die "docker missing — run bootstrap.sh first"

TAIGA_DIR=/opt/taiga-docker
rand() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c "$1"; }

if [[ ! -d "$TAIGA_DIR" ]]; then
    log "Cloning official taiga-docker"
    apt-get install -y git >/dev/null
    git clone https://github.com/taigaio/taiga-docker.git "$TAIGA_DIR"
fi
cd "$TAIGA_DIR"

if [[ ! -f .env.local-done ]]; then
    log "Writing .env with generated secrets"
    cat > .env <<EOF
# Generated by setup-taiga.sh — Taiga config reference:
# https://github.com/taigaio/taiga-docker
TAIGA_SCHEME=http
TAIGA_DOMAIN=taiga.home.lan
SUBPATH=""
WEBSOCKETS_ENABLED=true
SECRET_KEY="$(rand 48)"

POSTGRES_USER=taiga
POSTGRES_PASSWORD=$(rand 32)

# no SMTP at home — registration/invite mails print to the container log:
#   docker logs taiga-back
EMAIL_BACKEND=console

RABBITMQ_USER=taiga
RABBITMQ_PASS=$(rand 32)
RABBITMQ_VHOST=taiga
RABBITMQ_ERLANG_COOKIE=$(rand 32)

ENABLE_TELEMETRY=false
EOF
    chmod 600 .env
    touch .env.local-done
else
    log ".env already configured — keeping it"
fi

log "Starting Taiga (first start pulls several images)"
docker compose up -d

echo
log "Taiga starting at http://taiga.home.lan (gateway :9000)."
echo "  Create your admin account (run AFTER taiga-back is healthy, ~1 min):"
echo "    cd ${TAIGA_DIR} && ./taiga-manage.sh createsuperuser"
echo "  Then log in and create your first project. Public registration is"
echo "  off by default — add users from the admin panel (/admin/)."
