#!/usr/bin/env bash
# Configure this node's two 10 GbE ports as the routed full-mesh Ceph network
# (docs/02-network.md). Run on EVERY node after cabling the triangle:
#
#   node1:portX → node2:portY,  node2:portX → node3:portY,  node3:portX → node1:portY
#
#   bash 00-ceph-mesh-network.sh <iface-to-NEXT-node> <iface-to-PREV-node>
#   e.g. on node1:  bash 00-ceph-mesh-network.sh enp1s0f0 enp1s0f1
#
# Appends the mesh stanza to /etc/network/interfaces (backing it up first)
# and applies with ifreload.

source "$(dirname "$0")/lib.sh"
require_root
require_pve

IF_NEXT="${1:-}"
IF_PREV="${2:-}"
IFACES_FILE=/etc/network/interfaces

[[ -n "$IF_NEXT" && -n "$IF_PREV" ]] || die "usage: $0 <iface-to-next-node> <iface-to-prev-node>"
[[ "$IF_NEXT" != "$IF_PREV" ]] || die "the two interfaces must differ"
for ifc in "$IF_NEXT" "$IF_PREV"; do
    ip link show "$ifc" >/dev/null 2>&1 || die "interface '$ifc' not found (see: ip -br link)"
done

IDX="$(this_node_index)"
[[ -n "$IDX" ]] || die "hostname $(hostname) not in NODE_NAMES (cluster.env)"
[[ "${#CEPH_IPS[@]}" -eq "${#NODE_NAMES[@]}" ]] || die "CEPH_IPS not configured in cluster.env"

NEXT=$(( (IDX + 1) % ${#NODE_NAMES[@]} ))
PREV=$(( (IDX + 2) % ${#NODE_NAMES[@]} ))
MY_IP="${CEPH_IPS[$IDX]}"
NEXT_IP="${CEPH_IPS[$NEXT]}"
PREV_IP="${CEPH_IPS[$PREV]}"

STANZA="
# --- Ceph full-mesh network (generated by 00-ceph-mesh-network.sh) ---
auto ${IF_NEXT}
iface ${IF_NEXT} inet static
    address ${MY_IP}/24
    mtu ${MESH_MTU}
    up ip route add ${NEXT_IP}/32 dev ${IF_NEXT}
    down ip route del ${NEXT_IP}/32

auto ${IF_PREV}
iface ${IF_PREV} inet static
    address ${MY_IP}/24
    mtu ${MESH_MTU}
    up ip route add ${PREV_IP}/32 dev ${IF_PREV}
    down ip route del ${PREV_IP}/32
# --- end Ceph mesh ---"

if grep -q "generated by 00-ceph-mesh-network.sh" "$IFACES_FILE"; then
    die "mesh config already present in ${IFACES_FILE} — edit/remove it manually to reconfigure"
fi
for ifc in "$IF_NEXT" "$IF_PREV"; do
    ! grep -qE "^[[:space:]]*iface[[:space:]]+${ifc}[[:space:]]" "$IFACES_FILE" \
        || die "${ifc} is already configured in ${IFACES_FILE}"
done

echo "This node : ${NODE_NAMES[$IDX]} → mesh IP ${MY_IP}"
echo "  ${IF_NEXT} → ${NODE_NAMES[$NEXT]} (${NEXT_IP})"
echo "  ${IF_PREV} → ${NODE_NAMES[$PREV]} (${PREV_IP})"
echo "$STANZA"
echo
confirm "Append this to ${IFACES_FILE} and apply?" || die "aborted"

cp -a "$IFACES_FILE" "${IFACES_FILE}.bak.$(date +%s)"
echo "$STANZA" >> "$IFACES_FILE"
ifreload -a
log "Applied. Interface state:"
ip -br addr show "$IF_NEXT" "$IF_PREV"

echo
log "Once the peer nodes are configured too, verify:"
echo "  ping -c2 ${NEXT_IP} && ping -c2 ${PREV_IP}"
echo "  ping -c2 -M do -s $(( MESH_MTU - 28 )) ${NEXT_IP}   # jumbo frames pass"
